//! Where duplicates may be looked for, and what to do with the copies.
//!
//! A duplicate rule is a clean rule plus a keeper policy, and minus the meaning
//! of its parts. For a clean rule the parts are **matchers**: anything
//! satisfying any of them is claimed, independently. Here they are a
//! **population**: everything satisfying any of them is pooled, and duplicates
//! are searched *within that pool*. Adding a part to a clean rule adds
//! candidates; adding a part here can create groups that did not exist, because
//! two populations can now pair.
//!
//! **Membership is exclusive**: the first rule, in list order, whose parts match
//! a file takes it. Overlapping pools are not an ambiguity but a corrupt plan —
//! one pool would name a file its keeper while another listed it for removal,
//! and both would end up in the same merged plan. Exclusivity also makes the
//! keeper policy and the tier unambiguous by construction: a group cannot span
//! two rules, so there is nothing to resolve.
//!
//! The matching itself is [`Rules`]'. The two kinds of rule ask the same
//! question of a path and differ only in what they carry beside the answer, so
//! there is one automaton and one set of predicates rather than two that could
//! drift.

use crate::duplicates::Keep;
use crate::rules::{Facts, Part, Rule, RuleError, Rules, Tier, UserDirs};
use std::path::{Path, PathBuf};

/// One pool: where to look, and what to do with what is found there.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DuplicateRule {
    /// Unique among duplicate rules, and the name the report carries. It may
    /// coincide with a clean rule's — the two never appear in one plan.
    pub name: String,

    /// What `clean` does with the copies. `Trash` or `Confirm`; `Purge` is
    /// refused by the config layer, because a duplicate's content is
    /// regenerated by nothing and the other copy is the only thing that makes
    /// removing it safe.
    pub tier: Tier,

    pub enabled: bool,

    /// Which copy stays. `None` defers to the caller's default.
    pub keep: Option<Keep>,

    /// Preferred roots, in order, beating [`Self::keep`].
    pub keep_in: Vec<PathBuf>,

    /// Everything any of them matches is one pool.
    pub parts: Vec<Part>,
}

impl Default for DuplicateRule {
    fn default() -> Self {
        DuplicateRule {
            name: String::new(),
            tier: Tier::Confirm,
            enabled: true,
            keep: None,
            keep_in: Vec::new(),
            parts: Vec::new(),
        }
    }
}

/// The duplicate rules, compiled once for the whole search.
#[derive(Debug, Clone, Default)]
pub struct DuplicateRules {
    /// The matching, borrowed whole from the clean rules' engine.
    matching: Rules,
    /// What each surviving rule carries beside its patterns, positionally.
    policy: Vec<Policy>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Policy {
    keep: Option<Keep>,
    keep_in: Vec<PathBuf>,
}

/// What a pool says about the copies in it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pool<'a> {
    /// Which rule this is, by position — the identity a group is keyed on.
    pub index: usize,
    pub name: &'a str,
    pub tier: Tier,
    pub keep: Option<Keep>,
    pub keep_in: &'a [PathBuf],
    /// Below this the file is never opened. The part's, not the rule's.
    pub min_size: u64,
}

impl DuplicateRules {
    /// Compile `rules` against this user's directories.
    ///
    /// A part whose root cannot be resolved is dropped and the rest stand; a
    /// rule left with no parts is dropped whole — the same reading of "cannot be
    /// expressed" the clean rules use, and for the same reason.
    pub fn new(rules: Vec<DuplicateRule>, dirs: &UserDirs) -> Result<Self, RuleError> {
        // Carried through the clean-rule engine, which needs a `Rule` — the
        // policy travels beside it rather than through it, because a tier and a
        // keeper policy are different kinds of answer.
        let carried: Vec<Rule> = rules
            .iter()
            .map(|rule| Rule {
                name: rule.name.clone(),
                tier: rule.tier,
                enabled: rule.enabled,
                parts: rule.parts.clone(),
            })
            .collect();
        let matching = Rules::new(carried, dirs)?;

        // Only the rules that survived, in the order they survived in — which is
        // what makes `rule_index_at` line up with this.
        let kept: Vec<String> = matching.names();
        let policy = kept
            .iter()
            .filter_map(|name| rules.iter().find(|rule| &rule.name == name))
            .map(|rule| Policy {
                keep: rule.keep,
                keep_in: rule.keep_in.clone(),
            })
            .collect();

        Ok(DuplicateRules { matching, policy })
    }

    /// The one shipped rule: everywhere, less `.git`.
    ///
    /// Git LFS stores its objects **verbatim**, so every tracked file pairs with
    /// its own object under `.git/lfs/objects/` — a group where neither side may
    /// go. It is data rather than a hardcoded skip so that it is visible in
    /// `config init` and editable, exactly like the clean rules.
    pub fn builtin(dirs: &UserDirs) -> Self {
        DuplicateRules::new(builtin_duplicate_rules(), dirs).expect("built-in globs are valid")
    }

    pub fn is_empty(&self) -> bool {
        self.matching.is_empty()
    }

    /// The compiled rules, for a caller that wants to show them.
    pub fn compiled(&self) -> &crate::rules::Rules {
        &self.matching
    }

    /// A pool by the index [`Pool::index`] carried.
    ///
    /// The same position the file was admitted under, so this cannot name a
    /// different rule than the one that admitted it. `None` only if a caller
    /// invents an index.
    pub fn at(&self, index: usize) -> Option<Pool<'_>> {
        let name = self.matching.names().into_iter().nth(index)?;
        let rule = self.matching.get(&name)?;
        let policy = self.policy.get(index)?;
        Some(Pool {
            index,
            name: &self.matching.get(&name)?.name,
            tier: rule.tier,
            keep: policy.keep,
            keep_in: &policy.keep_in,
            // Not a part's: this is the rule, asked about without a path in
            // hand. The floor was applied when the file was admitted.
            min_size: 0,
        })
    }

    /// Where a `--dup` run with no path looks: the roots of every part, merged
    /// so none contains another.
    pub fn scan_roots(&self) -> Vec<PathBuf> {
        self.matching.scan_roots()
    }

    /// Can nothing under this directory be compared?
    ///
    /// Two ways to be sure: no rule's territory reaches here at all, or every
    /// rule that reaches here names the directory to be left alone. The second
    /// is what keeps a repository's own storage out of the walk rather than only
    /// out of the answer.
    pub fn prunes(&self, dir: &Path) -> bool {
        self.matching.prunes(dir) || self.matching.excludes_subtree(dir)
    }

    /// The pool this file belongs to — the **first** rule whose parts match it.
    ///
    /// `None` means it is not compared at all. Exclusive by construction: a file
    /// is in one pool or none, so no plan can both keep and remove it.
    pub fn pool(&self, path: &Path, facts: &Facts<'_>) -> Option<Pool<'_>> {
        let part = self.matching.claiming(path, facts)?;
        let index = self.matching.rule_index_at(part);
        let rule = self.matching.rule_at(part);
        let policy = &self.policy[index];
        Some(Pool {
            index,
            name: &rule.name,
            tier: rule.tier,
            keep: policy.keep,
            keep_in: &policy.keep_in,
            min_size: self.matching.part_at(part).min_size,
        })
    }
}

/// The duplicate rules this project ships.
///
/// One, and it says "everywhere except inside a repository's own storage".
pub fn builtin_duplicate_rules() -> Vec<DuplicateRule> {
    vec![DuplicateRule {
        name: "everywhere".into(),
        tier: Tier::Confirm,
        parts: vec![Part {
            includes: vec!["**".into()],
            // LFS keeps its objects byte-for-byte, so every tracked file has a
            // twin in here. Neither side may go: removing the working file
            // breaks the checkout, removing the object breaks the repository.
            //
            // Both spellings: the trailing `/` names the directory, which is
            // what stops the walk, and `/**` names what is inside it, which is
            // what stops the comparison.
            excludes: vec!["**/.git/".into(), "**/.git/**".into()],
            ..Part::default()
        }],
        ..DuplicateRule::default()
    }]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;

    fn facts<'a>(siblings: &'a [&'a str]) -> Facts<'a> {
        Facts {
            is_dir: false,
            modified: None,
            now: std::time::SystemTime::UNIX_EPOCH,
            any_sibling: Box::leak(Box::new(move |wanted: &dyn Fn(&OsStr) -> bool| {
                siblings.iter().any(|name| wanted(OsStr::new(name)))
            })),
        }
    }

    fn rule(name: &str, root: &str, includes: &[&str]) -> DuplicateRule {
        DuplicateRule {
            name: name.into(),
            parts: vec![Part {
                root: (root != "*").then(|| root.to_owned()),
                includes: includes.iter().map(|s| (*s).to_owned()).collect(),
                ..Part::default()
            }],
            ..DuplicateRule::default()
        }
    }

    fn compiled(rules: Vec<DuplicateRule>) -> DuplicateRules {
        DuplicateRules::new(rules, &UserDirs::default()).expect("compiles")
    }

    fn pool_of<'a>(rules: &'a DuplicateRules, path: &str) -> Option<&'a str> {
        rules
            .pool(Path::new(path), &facts(&[]))
            .map(|pool| pool.name)
    }

    /// The property "no intersections are needed" rests on: a file is in one
    /// pool or none, so no plan can name it a keeper and a candidate at once.
    #[test]
    fn the_first_rule_that_matches_takes_the_file() {
        let rules = compiled(vec![
            rule("photos", "/home/me/Photos", &["**"]),
            rule("everywhere", "*", &["**"]),
        ]);

        assert_eq!(pool_of(&rules, "/home/me/Photos/a.jpg"), Some("photos"));
        assert_eq!(
            pool_of(&rules, "/home/me/Downloads/a.jpg"),
            Some("everywhere"),
            "the broad rule takes what the narrow one did not"
        );
    }

    /// Order is the whole of it, so reversing it reverses the answer.
    #[test]
    fn the_order_is_the_precedence() {
        let rules = compiled(vec![
            rule("everywhere", "*", &["**"]),
            rule("photos", "/home/me/Photos", &["**"]),
        ]);

        assert_eq!(pool_of(&rules, "/home/me/Photos/a.jpg"), Some("everywhere"));
    }

    #[test]
    fn a_file_no_rule_matches_is_in_no_pool() {
        let rules = compiled(vec![rule("photos", "/home/me/Photos", &["**"])]);

        assert_eq!(pool_of(&rules, "/home/me/Downloads/a.jpg"), None);
    }

    /// Two parts, one pool: that is what lets a copy in the library and a copy
    /// in the downloads be compared with each other at all.
    #[test]
    fn two_parts_of_one_rule_are_one_pool() {
        let rules = compiled(vec![DuplicateRule {
            name: "library-and-copies".into(),
            parts: vec![
                Part {
                    root: Some("/home/me/Photos".into()),
                    includes: vec!["**".into()],
                    ..Part::default()
                },
                Part {
                    root: Some("/home/me/Downloads".into()),
                    includes: vec!["**".into()],
                    ..Part::default()
                },
            ],
            ..DuplicateRule::default()
        }]);

        let one = rules
            .pool(Path::new("/home/me/Photos/a.jpg"), &facts(&[]))
            .expect("in a pool");
        let two = rules
            .pool(Path::new("/home/me/Downloads/a.jpg"), &facts(&[]))
            .expect("in a pool");
        assert_eq!(one.index, two.index, "one pool, so they can pair");
    }

    /// The floor is the part's: two parts of one rule may read different
    /// amounts of disk.
    #[test]
    fn the_floor_comes_from_the_part_that_matched() {
        let rules = compiled(vec![DuplicateRule {
            name: "mixed".into(),
            parts: vec![
                Part {
                    root: Some("/big".into()),
                    includes: vec!["**".into()],
                    min_size: 1 << 20,
                    ..Part::default()
                },
                Part {
                    root: Some("/small".into()),
                    includes: vec!["**".into()],
                    min_size: 1024,
                    ..Part::default()
                },
            ],
            ..DuplicateRule::default()
        }]);

        let floor = |path: &str| {
            rules
                .pool(Path::new(path), &facts(&[]))
                .expect("in a pool")
                .min_size
        };
        assert_eq!(floor("/big/a.bin"), 1 << 20);
        assert_eq!(floor("/small/a.bin"), 1024);
    }

    /// The policy is the rule's, and it survives compilation in the same order
    /// the rules do — which is what `rule_index_at` is lined up against.
    #[test]
    fn each_pool_carries_its_own_policy() {
        let rules = compiled(vec![
            DuplicateRule {
                keep: Some(Keep::NewestModified),
                keep_in: vec![PathBuf::from("/home/me/Photos")],
                ..rule("photos", "/home/me/Photos", &["**"])
            },
            DuplicateRule {
                tier: Tier::Trash,
                ..rule("everywhere", "*", &["**"])
            },
        ]);

        let photos = rules
            .pool(Path::new("/home/me/Photos/a.jpg"), &facts(&[]))
            .expect("in a pool");
        assert_eq!(photos.keep, Some(Keep::NewestModified));
        assert_eq!(photos.keep_in, [PathBuf::from("/home/me/Photos")]);
        assert_eq!(photos.tier, Tier::Confirm);

        let elsewhere = rules
            .pool(Path::new("/elsewhere/a.jpg"), &facts(&[]))
            .expect("in a pool");
        assert_eq!(elsewhere.keep, None);
        assert!(elsewhere.keep_in.is_empty());
        assert_eq!(elsewhere.tier, Tier::Trash, "a pool may say trash");
    }

    /// A rule whose every part dropped is gone, and the policy list must not
    /// slip: the rule after it keeps its own.
    #[test]
    fn a_dropped_rule_does_not_shift_the_policies() {
        let rules = DuplicateRules::new(
            vec![
                DuplicateRule {
                    keep: Some(Keep::First),
                    ..rule("needs-home", "~", &["**"])
                },
                DuplicateRule {
                    keep: Some(Keep::NewestCreated),
                    ..rule("everywhere", "*", &["**"])
                },
            ],
            // No home, so the first rule cannot be expressed at all.
            &UserDirs::default(),
        )
        .expect("compiles");

        let pool = rules
            .pool(Path::new("/anywhere/a.jpg"), &facts(&[]))
            .expect("in a pool");
        assert_eq!(pool.name, "everywhere");
        assert_eq!(
            pool.keep,
            Some(Keep::NewestCreated),
            "the surviving rule keeps its own policy, not the dropped one's"
        );
    }

    /// The shipped rule, and the reason it exists.
    #[test]
    fn the_builtin_searches_everywhere_but_a_repository_store() {
        let rules = DuplicateRules::builtin(&UserDirs::default());

        assert_eq!(pool_of(&rules, "/home/me/a.jpg"), Some("everywhere"));
        assert_eq!(
            pool_of(&rules, "/home/me/repo/.git/lfs/objects/ab/cd/ef"),
            None,
            "LFS keeps its objects verbatim, so every tracked file has a twin here"
        );
        assert!(
            rules.prunes(Path::new("/home/me/repo/.git")),
            "and the walk stops at the directory rather than reading all of it"
        );
        assert!(
            !rules.prunes(Path::new("/home/me/repo")),
            "but not one step above it"
        );
    }
}
